astraly-labs/pragma-sdk

- pragma/core/assets.py
- pragma/publisher/fetchers/__init__.py
- pragma/publisher/fetchers/defillama.py
- pragma/publisher/fetchers/gecko.py
- pragma/publisher/future_fetchers/binance.py
- pragma/tests/constants.py
- pragma/tests/fetchers_test.py
- pragma/tests/mock/responses/gecko.json
- pragma/tests/publisher_test.py
- Adds [GeckoTerminal](https://www.geckoterminal.com/dex-api) API Fetcher
- Adds support for R and LORDS
> ✨ GeckoTerminal Fetcher

- CONTRIBUTING.md
- README.md
Add documentation on setting up the `pragma-sdk` repo and how to run tests locally.
> ✍️ Add docs on setup and running tests locally

- pragma/core/mixins/offchain.py
Adds a `load_ssl_context` method on `OffchainMixin`
The Pragma API is protected via mutual TLS authentication. 
This PR adds an easy way for data providers/consumers to fill their certificate/key to the SDK before interacting with the API.
> ✨ load_ssl_context (offchain_mixin)

- pragma/core/client.py
- pragma/core/mixins/offchain.py
Adds support for `x-api-key` authorization scheme when interacting with Pragma API.
> ✨ (offchain) api_key support

- pragma/core/assets.py
- pragma/core/client.py
- pragma/core/contract.py
- pragma/core/types.py
- pragma/publisher/fetchers/starknetamm.py
- pragma/tests/constants.py
- pragma/tests/fetcher_configs.py
- pragma/tests/fetchers_test.py
- pragma/tests/mock/responses/on_starknet_amm.json
- pyproject.toml
> Starknet fetcher improvements and tests

- pragma/publisher/fetchers/__init__.py
- pragma/publisher/fetchers/propeller.py
- pragma/tests/fetcher_configs.py
- pragma/tests/mock/responses/propeller.json
Adds support for Propeller Heads [API](https://docs.propellerheads.xyz/propellerheads-docs/solver-api/api-reference-v2).
> ✨ Propeller Heads Fetcher

- pragma/publisher/fetchers/defillama.py
> Defillama api key support

- pragma/core/mixins/oracle.py
- pragma/core/types.py
- pragma/publisher/fetchers/bybit.py
- pragma/publisher/fetchers/defillama.py
- pragma/publisher/fetchers/gecko.py
- pragma/publisher/fetchers/propeller.py
- pragma/publisher/fetchers/starknetamm.py
- pragma/publisher/future_fetchers/binance.py
- pragma/publisher/future_fetchers/bybit.py
- pragma/publisher/future_fetchers/okx.py
- pragma/publisher/types.py
- pyproject.toml
- stagecoach/jobs/publishers/starknet_publisher/Dockerfile.dev
- stagecoach/jobs/publishers/starknet_publisher/app.py
Adds 2 conditions upon which the publishing can happen:
1. Check time since last publish for the given publisher
2. Check deviation of the current on-chain median price from Defillama's API
> ✨ deviation + time threshold

- poetry.lock
- pragma/core/client.py
- pragma/core/contract.py
- pragma/core/entry.py
- pragma/core/mixins/oracle.py
- pragma/core/mixins/publisher_registry.py
- pragma/core/mixins/randomness.py
- pragma/core/randomness/utils.py
- pragma/publisher/types.py
- pragma/tests/fixtures/clients.py
- pragma/tests/utils.py
- pragma/tests/vrf_test.py
- pyproject.toml
- Updates starknet.py to 0.20.0
- Fixes `NonceMixin` usage to avoid nonce duplicate issues
> 🐛 fix nonce duplicate issue + upgrade starknet.py

- pragma/core/assets.py
- pragma/core/client.py
- pragma/core/entry.py
- pragma/core/types.py
- pragma/publisher/client.py
- pragma/publisher/fetchers/__init__.py
- pragma/publisher/fetchers/binance.py
- pragma/publisher/fetchers/defillama.py
- pragma/publisher/fetchers/gecko.py
- pragma/publisher/fetchers/index.py
- pragma/publisher/fetchers/indexcoop.py
- pragma/publisher/fetchers/propeller.py
- pragma/tests/constants.py
- pragma/tests/fetcher_configs.py
- pragma/tests/fetchers_test.py
- pragma/tests/mock/responses/indexcoop.json
- pragma/tests/utils.py
- pyproject.toml
- stagecoach/jobs/publishers/starknet_publisher/app.py
- Adds a new fetcher `IndexCoopFetcher` to fetch data from the IndexCoop API
> ✨ IndexCoop Fetcher

- .github/workflows/checks.yml
- pragma/core/assets.py
- pragma/publisher/fetchers/__init__.py
- pragma/publisher/fetchers/gateio.py
- pragma/publisher/fetchers/mexc.py
- pyproject.toml
- stagecoach/jobs/publishers/starknet_publisher/app.py
> feat: gate io and mexc fetchers

- pragma/core/types.py
- pragma/publisher/fetchers/gecko.py
- pragma/publisher/fetchers/starknetamm.py
- pyproject.toml
- Adds support for NSTR token in Defillama/GeckoTerminal/Starknet Fetchers
> feat: add NSTR support

- price-pusher/price_pusher/core/request_handlers/api.py
- price-pusher/price_pusher/orchestrator.py
- Added the fetching of future data from the offchain api
##
it push all data (perp and non perp) but only compare to perps
> Next pp add future endpoint

- pragma-sdk/tests/unit/index_aggregation_test.py
-  implemented index aggregagtor test
> fixing test

- .github/workflows/docker-build.yml
- .github/workflows/linters.yml
- .github/workflows/publish.yml
- .github/workflows/pull-request.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
- Fix env var from workflows
- delete artifacts from `docker-build` jobs
##
> fix: env variables, rm artifacts for release

- .github/workflows/docker-build.yml
- .github/workflows/publish.yml
- use github env format for `PACKAGE_VERSION` 
- add `matrix` and change `poetry` installation order
##
> fix: workflows publisher, docker-build

- .github/workflows/publish.yml
- add `id-token` permission into `publisher` workflow
##
> feat: add id-token permission

- infra/price-pusher/Dockerfile
- infra/price-pusher/buildspec.yml
- infra/price-pusher/config.yml
- infra/price-pusher/config/config.yaml
- infra/vrf-listener/Dockerfile
- infra/vrf-listener/buildspec.yml
- infra/vrf-listener/config.yml
- Add `buildspec` for `vrf-listener` and `price-pusher`
- Specific `Dockerfile` for deployment with default params
##
> feat: add infra folder for deployments

- .github/workflows/tests.yml
- Fix the current error on tests workflows
##
> fix: ci-tests error

- .github/workflows/pre-release.yml
- .github/workflows/publish.yml
- .github/workflows/tests.yml
- fix `starknet-devnet` binary installation and existing tags issue in publishment
##
> fix: CI tests and pre-release

- .github/workflows/pre-release.yml
- .github/workflows/publish.yml
- .github/workflows/tests.yml
- Fix `starknet-devnet` installation on CI
##
> fix: CI tests

- pragma-sdk/pragma_sdk/onchain/client.py
- price-pusher/price_pusher/main.py
Closes #
- Fixed price-pusher import
##
> hotfix: `price-pusher` import

- price-pusher/price_pusher/core/request_handlers/chain.py
Closes #
- On chain fetches latest price from PENDING
> hotfix(price_pusher): Fixed block

- pragma-sdk/docs/source/index.rst
- pragma-sdk/docs/source/migration.rst
- pragma-sdk/docs/source/quickstart.rst
Closes #
- Adds a migration guide from v1.x.x to v2.xx 
##
> feat: add migration guide to docs

- infra/merkle-maker/Dockerfile
- infra/merkle-maker/buildspec.yml
- infra/merkle-maker/config.yml
- add `merkle-maker` infra specs
##
> feat: merkle-maker buildspec

- infra/price-pusher/offchain/Dockerfile
- infra/price-pusher/offchain/config.yml
- remove useless `RPC_URL` param from `price-pusher-offchain`
##
> fix/infra: remove useless params

- infra/merkle-maker/Dockerfile
> Fix merkle maker docker entrypoint

- infra/vrf-listener/Dockerfile
- infra/vrf-listener/config.yml
- pragma-sdk/pragma_sdk/common/randomness/randomness_utils.py
- pragma-sdk/pragma_sdk/common/randomness/utils.py
- pragma-sdk/pragma_sdk/onchain/mixins/randomness.py
- pragma-sdk/pragma_sdk/onchain/types/types.py
- vrf-listener/benchmark/accounts.py
- vrf-listener/benchmark/contracts.py
- vrf-listener/benchmark/deploy.py
- vrf-listener/benchmark/devnet.py
- vrf-listener/benchmark/main.py
- vrf-listener/benchmark/pragma_client.py
- vrf-listener/benchmark/stresstest.py
- vrf-listener/poetry.lock
- vrf-listener/pyproject.toml
- vrf-listener/tests/integration/vrf_listener_test.py
- vrf-listener/vrf_listener/main.py
Closes #194 
- VRF benchmark, runnable with `poe benchmark`
- Multithreading for `randomness.handle_random`
- `submit_random_multicall` to submit all randomness
> dev: VRF optimizations + VRF listener benchmark

- pragma-sdk/pragma_sdk/onchain/mixins/randomness.py
- vrf-listener/vrf_listener/main.py
Closes #
- Wait for multicall tx in vrf listener
##
> hotfix: Await for multicall

- pragma-sdk/pragma_sdk/onchain/mixins/summary.py
> hotfix: twap computation

- infra/checkpointer/Dockerfile
- infra/checkpointer/buildspec.yml
- infra/checkpointer/config.yml
- infra/checkpointer/entrypoint.sh
> Move secrets of checkpointer to INFISICAL

- infra/price-pusher/pragma/Dockerfile
- infra/price-pusher/pragma/buildspec.yml
- infra/price-pusher/pragma/config.yml
- infra/price-pusher/pragma/entrypoint.sh
> feat:added price-pusher service infra for pragma

- infra/price-pusher/onchain/Dockerfile
- infra/price-pusher/onchain/config.yml
- infra/price-pusher/onchain/entrypoint.sh
> Price pusher onchain ci

- pragma-sdk/docs/source/quickstart.rst
The Quickstart code for fetching data gives multiple errors! Fixing it.
> Fix: fixing quickstart docs code

- infra/price-pusher/config/config.offchain.dev.yaml
- pragma-sdk/pragma_sdk/common/fetchers/future_fetchers/binance.py
- pragma-sdk/pragma_sdk/common/fetchers/future_fetchers/okx.py
- pragma-sdk/pragma_sdk/offchain/client.py
- pragma-sdk/pragma_sdk/supported_assets.yaml
- price-pusher/config/config.example.yaml
- price-pusher/price_pusher/configs/fetchers.py
- price-pusher/price_pusher/core/poller.py
Closes #
- Add support for all StarkEx assets
- Fix broken fetchers
##
> fix: starkex all assets

- infra/price-pusher/config/config.mainnet.yaml
- infra/price-pusher/config/config.sepolia.yaml
- pragma-sdk/pragma_sdk/common/fetchers/fetchers/__init__.py
- pragma-sdk/pragma_sdk/common/fetchers/fetchers/defillama.py
- pragma-sdk/pragma_sdk/common/fetchers/fetchers/dexscreener.py
- pragma-sdk/pragma_sdk/common/fetchers/fetchers/ekubo.py
- pragma-sdk/pragma_sdk/common/fetchers/fetchers/geckoterminal.py
- pragma-sdk/pragma_sdk/supported_assets.yaml
- pragma-sdk/tests/fetcher_test.py
- price-pusher/config/config.example.yaml
Closes #N/A
- Add support for new `USDPLUS` currency i.e USD with 18 decimals
- Adds a new script `fetcher_test.py` to easily test any fetcher 
- Fix fetchers to take into account this new currency
- Update price pusher configs to use `BROTHER/USDPLUS` pair
##
> feat: add USDPLUS support

- infra/price-pusher/config/config.offchain.dev.yaml
- pragma-sdk/pragma_sdk/common/fetchers/fetcher_client.py
- pragma-sdk/pragma_sdk/common/fetchers/future_fetchers/binance.py
- pragma-sdk/pragma_sdk/common/fetchers/future_fetchers/okx.py
- pragma-sdk/pragma_sdk/offchain/client.py
- pragma-sdk/pragma_sdk/supported_assets.yaml
- pragma-sdk/tests/fetcher_test.py
- price-pusher/config/config.example.yaml
- price-pusher/price_pusher/configs/fetchers.py
- price-pusher/price_pusher/core/poller.py
Closes #
- Adds all missing assets to `supported_assets.yml`
- Fix future fetchers to correctly fetch in //
- Update timeout to 5s in price-pusher for fetching
- Remove limits to connection pool size[¶](https://docs.aiohttp.org/en/stable/client_advanced.html#limiting-connection-pool-size)
##
> fix: starkex x10 full support
