pragma/core/client.py, pragma/core/types.py
Addresses #16 
@EvolveArt I could not find an RPC API provider that did not need an API key to operate so I've removed those options for now. Is there a pragma RPC API for mainnet and testnet? Or maybe something that will replace the soon-deprecated feeder gateway?
=> feat: add default rpc's and remove rpc_key env

pragma/core/client.py, pragma/core/utils.py, pragma/tests/client_test.py
addresses #33 
This PR fetches the chain ID from the Starknet RPC API when an RPC URL is given. As a result, it only returns `"testnet"` and `"mainnet"` chain IDs for now.
Another approach is to require users to pass in a data type that includes url and chain name.
=> fix: get client id for rpc url

pragma/core/client.py, pragma/core/mixins/__init__.py, pragma/core/mixins/offchain.py, pragma/publisher/client.py, pragma/publisher/fetchers/thegraph.py, pragma/tests/fetcher_configs.py, pragma/tests/fetchers_test.py, pragma/tests/mock/responses/thegraph.json, pragma/tests/offchain_mixin.py, stagecoach/jobs/tests/test_checkpoint.py, stagecoach/jobs/tests/test_custom.py, stagecoach/jobs/tests/test_starknet_publisher.py
Solves #37 
Adds basic support for fetching `SpotEntry` USD pairs from Uniswap V3 through TheGraph.
Future Action Items
--
=> ✨ TheGraph UniV3 Spot

pragma/core/mixins/offchain.py, stagecoach/jobs/publishers/checkpoint/app.py, stagecoach/jobs/publishers/starknet_publisher/app.py, stagecoach/jobs/randomness/app.py
In order to prevent replay attacks, we add the timestamp and expiration parameters to the signed message. It's also sent through the headers so the API can reconstruct the message and verify the signature.
=> ✨ add timestamp/expiry to publish msg

pragma/core/mixins/randomness.py, pyproject.toml
Ignores requests older than 30 blocks by default.
=> fix(vrf): ignore old requests

.github/workflows/publish.yml
- add `pypitest` environment
-  use `id-token` only for specific jobs
##
=> feat: pypi test jobs, better permissions management

price-pusher/price_pusher/main.py, vrf-listener/vrf_listener/main.py
Closes # 
- Fixed error for when the network is an RPC_URL, missed the chain_name
=> hotfix: Chain name in services

checkpointer/poetry.lock, checkpointer/pyproject.toml, poetry.lock, pragma-sdk/poetry.lock, pragma-sdk/pyproject.toml, pragma-utils/poetry.lock, pragma-utils/pyproject.toml, price-pusher/poetry.lock, price-pusher/pyproject.toml, pyproject.toml, vrf-listener/poetry.lock, vrf-listener/pyproject.toml
Closes NA
- Minimal version has to be `3.11` because we use `StrEnum` in the code
=> hotfix: Fixed python minimal required version

pragma-sdk/pragma_sdk/common/fetchers/fetchers/binance.py, pragma-sdk/pragma_sdk/common/fetchers/fetchers/bitstamp.py, pragma-sdk/pragma_sdk/common/fetchers/fetchers/bybit.py, pragma-sdk/pragma_sdk/common/fetchers/fetchers/coinbase.py, pragma-sdk/pragma_sdk/common/fetchers/fetchers/defillama.py, pragma-sdk/pragma_sdk/common/fetchers/fetchers/gateio.py, pragma-sdk/pragma_sdk/common/fetchers/fetchers/gecko.py, pragma-sdk/pragma_sdk/common/fetchers/fetchers/huobi.py, pragma-sdk/pragma_sdk/common/fetchers/fetchers/indexcoop.py, pragma-sdk/pragma_sdk/common/fetchers/fetchers/kucoin.py, pragma-sdk/pragma_sdk/common/fetchers/fetchers/mexc.py, pragma-sdk/pragma_sdk/common/fetchers/fetchers/okx.py, pragma-sdk/pragma_sdk/common/fetchers/fetchers/propeller.py, pragma-sdk/pragma_sdk/common/fetchers/fetchers/starknetamm.py, pragma-sdk/pragma_sdk/common/fetchers/fetchers/upbit.py, pragma-sdk/pragma_sdk/common/fetchers/future_fetchers/bybit.py, pragma-sdk/pragma_sdk/common/fetchers/future_fetchers/okx.py, pragma-sdk/pragma_sdk/onchain/mixins/oracle.py, price-pusher/config/config.example.yaml, price-pusher/price_pusher/core/listener.py, price-pusher/price_pusher/core/poller.py, price-pusher/price_pusher/core/pusher.py, price-pusher/price_pusher/orchestrator.py, price-pusher/tests/unit/core/test_listener.py, price-pusher/tests/unit/test_orchestrator.py
Closes #NA
- `pragma_sdk` sent entries message is now debug, allows us to opt out from it if we want
- logs: wrong source name + confusing price logged (was showing a lot of `0`). Now shows the bigdecimal price that we actually use in our entries.
- a `listener` now wait until a push event is successfully done before sending notification again,
- deviation showed in `listener` alert,
- `poller` filters out prices set to `0`
- `wait_for_acceptance` max retries set to 60 so we fail fast if the tx is lost into the oblivion
- `pusher` clear notification only after the push event is handled
- we now compare the median prices of all sources VS the oracle median price in the `listener`
=> fix: More price pusher fixes after Kakarot test

pragma-sdk/pragma_sdk/common/fetchers/fetchers/bitstamp.py, pragma-sdk/pragma_sdk/common/fetchers/fetchers/defillama.py, pragma-sdk/pragma_sdk/common/fetchers/fetchers/huobi.py, pragma-sdk/pragma_sdk/common/fetchers/fetchers/kucoin.py, pragma-sdk/pragma_sdk/common/fetchers/fetchers/okx.py, pragma-sdk/pragma_sdk/common/fetchers/fetchers/starknetamm.py, pragma-sdk/pragma_sdk/common/fetchers/future_fetchers/binance.py, pragma-sdk/pragma_sdk/common/fetchers/future_fetchers/bybit.py, pragma-sdk/pragma_sdk/common/fetchers/future_fetchers/okx.py, pragma-sdk/pragma_sdk/onchain/mixins/oracle.py, pragma-sdk/tests/integration/fetchers/fetcher_configs.py, price-pusher/config/config.example.yaml, price-pusher/price_pusher/configs/fetchers.py, price-pusher/price_pusher/core/listener.py, price-pusher/price_pusher/core/request_handlers/api.py, price-pusher/tests/unit/core/test_listener.py
Closes #
- All our fetchers now return the current timestamp for their `timestamp` column,
- Fixed `Ekubo` fetcher - URL was wrong
=> fix: Fixed some price pusher edge cases

infra/price-pusher/config/config.mainnet.yaml, infra/price-pusher/config/config.sepolia.yaml, pragma-sdk/pragma_sdk/onchain/mixins/nonce.py, price-pusher/price_pusher/core/pusher.py, price-pusher/price_pusher/orchestrator.py, price-pusher/tests/unit/test_orchestrator.py
Closes #NA
- Fixed concurrency issue when publishing on chain. We now have an `asyncio.Lock` that locks the creation of a new `nonce` exclusively to one thread, so we never run into a concurrency problem where two threads catch the same nonce. 
- Updates price pusher configs
=> fix: Price pusher concurrency issue onchain

checkpointer/pyproject.toml, checkpointer/tests/integration/checkpointer_test.py, pragma-sdk/pragma_sdk/onchain/types/contract.py
Closes #NA
- Added a lock when generating the nonce in `contract.py` so Accounts can't generate the same nonce.
- Fixed the infinite loop for the checkpointer
=> hotfix: Fixed race condition when generating nonce

pragma-sdk/pragma_sdk/common/types/entry.py, pragma-sdk/pragma_sdk/onchain/mixins/oracle.py, pragma-sdk/tests/integration/client_test.py, price-pusher/price_pusher/core/listener.py, price-pusher/price_pusher/core/request_handlers/api.py, price-pusher/price_pusher/core/request_handlers/chain.py, price-pusher/price_pusher/core/request_handlers/interface.py, price-pusher/tests/unit/core/test_listener.py
Closes #NA
- **sdk**: `get_data_entry` onchain call + test
- **price-pusher**: `fetch_latest_entries` now takes the sources we want to compute the median for.
=> fix: Price pusher median comparison

pragma-sdk/pragma_sdk/onchain/mixins/randomness.py, vrf-listener/vrf_listener/main.py
Closes #
- Fix bug in vrf listener where estimates fee is not done on pending block
##
=> hotfix: Fix estimate_fee

infra/vrf-listener/Dockerfile, pragma-sdk/pragma_sdk/onchain/mixins/randomness.py, vrf-listener/vrf_listener/indexer.py, vrf-listener/vrf_listener/listener.py, vrf-listener/vrf_listener/main.py
Closes #NA
- Added logs to check whats happening
- Retry system for failed VRF submissions
- fix `requests_events` condition check
##
All of our issues looks related to sync problems.
Breakdown:
1. We chose Apibara for indexing due to a lag in Starknet.py. There was a noticeable delay between event emission and our ability to retrieve it using the `get_event` function.
2. Upon further investigation, we realized this issue likely stems from our RPC choice rather than Starknet.py itself.
3. We're now dealing with a challenging synchronization scenario. There's an unpredictable gap between when an event is submitted and when it becomes accessible via the Fullnode. This creates various issues, with severity fluctuating based on our chosen RPC.
4. As a temporary solution, we've implemented a …
=> dev: Sync fighting + Logs

CHANGELOG.md, infra/vrf-listener/Dockerfile, infra/vrf-listener/config.yml, pragma-sdk/pragma_sdk/onchain/mixins/randomness.py, pragma-sdk/pragma_sdk/onchain/types/contract.py, pragma-sdk/tests/integration/vrf_test.py, vrf-listener/README.md, vrf-listener/benchmark/deploy.py, vrf-listener/benchmark/devnet/contracts.py, vrf-listener/benchmark/stress/stress_tester.py, vrf-listener/benchmark/stress/txs_spam.py, vrf-listener/vrf_listener/click_types.py, vrf-listener/vrf_listener/listener.py, vrf-listener/vrf_listener/main.py
Closes #NA
- Re-added mandatory fee check
- Multicall impl (without wait_for_tx)
- whitelist for which we don't check fees
Note: Adding `track_nonce` adds way to much unreliability. Better to loose a few seconds waiting for the tx than pilling up txs that will fail and retry requests.
##
=> fix: Mandatory VRF request fees estimation

pragma-sdk/pragma_sdk/common/fetchers/fetchers/dexscreener.py, pragma-sdk/pragma_sdk/onchain/constants.py, pragma-sdk/tests/integration/update_client_test.py
Closes #NA
`Dexscreener` fetcher was buggy (or the API changed, as they mentionned it is unstable) and was returning really low liquidity pairs. Hence price was wrong.
To fix that, we adjusted the endpoint and we are now only supporting USD quote assets - until the API is stable and we can choose something else for other quote assets.
Since 90% of our assets are quoted in USD, this is fine.
##
=> hotfix: Dexscreener fetcher

pragma-sdk/pragma_sdk/common/fetchers/fetchers/ekubo.py
Closes #NA
- The Ekubo fetcher does not raise errors when the quote currency address is zero. We added a check. (EUR is an abstract currency, hence starknet_address == 0, was returning 1 from the contract)
##
=> fix: Ekubo fetcher for quote_address == 0

price-pusher/price_pusher/core/listener.py, price-pusher/price_pusher/core/request_handlers/__init__.py, price-pusher/price_pusher/main.py, price-pusher/price_pusher/orchestrator.py, price-pusher/price_pusher/price_types.py, price-pusher/price_pusher/utils.py
Closes #N/A
- Fix circular dependency due to the use of `types.py` filename
- Update typing to support python 3.11.8
##
=> fix: price pusher circular deps

README.md, pragma-sdk/pragma_sdk/common/fetchers/fetchers/pyth.py, pragma-sdk/pragma_sdk/common/types/client.py, pragma-sdk/pragma_sdk/offchain/client.py, pragma-sdk/pragma_sdk/offchain/constants.py, pragma-sdk/pragma_sdk/offchain/signer.py, pragma-sdk/pyproject.toml, price-pusher/price_pusher/core/pusher.py, price-pusher/price_pusher/main.py, price-pusher/tests/unit/core/test_pusher.py, price-pusher/uv.lock
Closes #N/A
- Add a new `--websocket-url` option to the price pusher to publish on the API websocket endpoint
- Websocket publishing supports authentication by sending `login` message
_TODO_ 
- pass the session in the api client instead of opening a new connection every time
- add `--burst` mode to price pusher to send data in the channel as soon as its available instead of waiting to produce a batch
##
=> feat: websocket publishing w/ auth

checkpointer/README.md, lp-pricer/README.md, merkle-maker/README.md, price-pusher/README.md, vrf-listener/README.md
Closes #
- Corrected "ran" to "run" in multiple docs for proper passive voice usage (e.g., "is ran" → "is run").
##
=> docs: fix typos

lmax-connector/README.md
Closes #
- Corrected "ddocker build" to "docker build"
##
=> fix: build command typo README.md
